name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ./Simple_report/Simple_report.tex
          
#./Simple_report/Simple_report.tex
# Esto va comentado por ahora que no anda
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: PDF
      #     path: ./Simple_report/main.pdf
      # - name: Download a Build Artifact
      #   uses: actions/download-artifact@v2.0.9
      #   with: 
      #     name: PDF 
      #     path: path/to/PDF
