name: Build LaTeX document
on: [push]
jobs:
  build_main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            ./Simple and elegant report/main.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: ./Simple and elegant report/main.pdf
